### PR TITLE
Allow assigning values to parameters

### PR DESCRIPTION
**Pull request by johnsardine**
Hello,

I felt the need to get a value associated to a parameter so I added it to the project.

I hope you find this useful.

Please let me know if there are any changes that I should make to this PR.

Thanks for the project

### CODE REVIEW

**Comment by thomaschampagne** [comment]
@johnsardine Very thanks for this ! Merged ;)

I will update npm package

Thanks again ;)

**Comment by thomaschampagne** [comment]
@johnsardine I pushed npm release 1.1.0.

I updated my projects using your PR. But i got this error:

```
C:\projects\stravistix\node_modules\gulp-options\index.js:10
                [param, value] = p.replace('--', '').split('=');
                ^
ReferenceError: Invalid left-hand side in assignment
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\projects\stravistix\gulpfile.js:32:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
Command exited with code 1
```

Does that talk to you? Are you experiencing same problem?

build link: https://ci.appveyor.com/project/thomaschampagne/stravistix/build/10

Thanks again ;)

Tom

**Comment by johnsardine** [comment]
Hi Tom. Can you tell me what version of npm and gulp you're using so I can reproduce on my side? I used a couple of new JavaScript features. That may be the issue. If I find it's the case, I'll write a more compatible version and issue a PR. Thanks, Joao

**Comment by thomaschampagne** [comment]
Re @johnsardine,

Thanks for your quick response :)

Here are versions used on my continious integration  (https://ci.appveyor.com) where problem occurs
- node@v4.6.1
- gulp-cli@1.2.2
- gulp@3.9.1

I don't have any problems on my windows 10 + Ubuntu 16.04 with node in version 6.9.x.

Maybe an error from node 4.x ?!

Thanks again for yor work ;)

Tom

**Comment by johnsardine** [comment]
@thomaschampagne I have made some adjustments. It works with node 4 now. There is no reason to break compatibility just because of a simpler syntax. Maybe in the future :)

Take a look #2

**Pull request merged**
